MCKIN-24383 xblock internationalization
open-craft/xblock-group-project-v2 pull request #148
Opened 2020-11-13 11:12 UTC by mudassir-hafeez

Group project v2 internationalization.

2020-11-13 23:20 UTC, viadanna commented
Hello @mudassir-hafeez can you provide a brief description of the changes and testing instructions?

Also, there are some issues that prevent CI testes passing, can you check those?

2020-11-19 05:11 UTC, xitij2000 commented
@mudassir-hafeez Could you look at the test failures here. They seem to be due to minor isort issues. 

I'll review this shortly.

2020-11-19 08:48 UTC, mudassir-hafeez commented
@xitij2000 fixed the isort issue. Can you please review?

2020-11-19 10:26 UTC, xitij2000 commented
@mudassir-hafeez Does this need to go only on juniper? If not, then it might make sense to also create a PR against the v0.10 branch.

2020-11-19 12:06 UTC, xitij2000 requested changes
This seems mostly good to go, just need some minor changes.

2020-11-19 12:06 UTC, xitij2000 commented on pylintrc
> + invalid-name,
This is overly broad, remove this.

2020-11-19 12:06 UTC, xitij2000 commented on pylintrc
> +#method-rgx=_?[a-z_][a-z0-9_]{2,40}$
I think the options here are pretty descriptive, so no need for additional comments. 
```suggestion
method-naming-style=snake_case
```

2020-11-19 12:06 UTC, xitij2000 commented on setup.py
> +    version='0.11.1',
This includes pretty big changes so I suggest we bump the minor version. 
```suggestion
    version='0.12.0',
```

2020-11-19 21:08 UTC, mudassir-hafeez commented
@xitij2000 suggestions have been addressed. Here #152 is the actual PR against v0.10. Can you please review and create a release tag?

2020-11-20 14:51 UTC, xitij2000 approved these changes
:+1:
- [x] I tested this: tested on juniper solution devstack
- [x] I read through the code
- [na] I checked for accessibility issues
- [na] Includes documentation

2020-11-20 14:55 UTC, merged